/**
 * Deterministic generative identicons with lineage.
 *
 * Ported from the original build, which used these to make a request VISUALLY
 * traceable: you could watch one identicon leave a client, split into recoloured
 * offspring at a fan-out, and watch those offspring return to the row that had been
 * holding a slot open for them. That readability is the best idea in the old codebase
 * and it survives the rewrite intact.
 *
 * What changed is where the sprite comes from. Previously the animation *was* the
 * model, so the icons were generated by the engine as it ran. Now they are derived
 * purely from a recorded trace: the same request id always produces the same icon,
 * so replaying a trace twice looks identical, and nothing about the visuals can
 * influence what was simulated.
 *
 * LINEAGE KEEPS THE SHAPE AND CHANGES THE HUE
 *
 * A child reads as "the same request, recoloured" rather than as a different request.
 * That was a deliberate choice in the original and it is the property that makes a
 * fan-out legible: five sprites of one shape in five colours are obviously siblings,
 * while five different shapes are just noise.
 */

const GRID = 5;
/** Left half including the centre column; the right half mirrors it. */
const COLS = 3;

export interface Identicon {
  /** Left half of the pattern, `grid[row][col]`. */
  grid: boolean[][];
  hue: number;
  /** Stable cache key. Also encodes lineage. */
  key: string;
  error: boolean;
}

function fnv(input: string): number {
  let h = 2166136261 >>> 0;
  for (let i = 0; i < input.length; i++) {
    h ^= input.charCodeAt(i);
    h = Math.imul(h, 16777619) >>> 0;
  }
  return h >>> 0;
}

function mulberry32(seed: number): () => number {
  let a = seed | 0;
  return () => {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** The icon for a root request. Same id always gives the same icon. */
export function rootIcon(seed: number | string): Identicon {
  const key = `r:${seed}`;
  const rng = mulberry32(fnv(key));
  const grid: boolean[][] = [];
  for (let r = 0; r < GRID; r++) {
    const row: boolean[] = [];
    for (let c = 0; c < COLS; c++) row.push(rng() > 0.45);
    grid.push(row);
  }
  // An almost-empty pattern is unreadable at sprite size, so guarantee some ink.
  let on = 0;
  for (const row of grid) for (const cell of row) if (cell) on++;
  if (on < 4) grid[Math.floor(rng() * GRID)]![1] = true;

  return { grid, hue: Math.floor(rng() * 360), key, error: false };
}

/**
 * A descendant: identical pattern, well-separated hue.
 *
 * The hue is pushed at least 70 degrees away from the parent so siblings are
 * distinguishable at a 20-pixel sprite, where subtle differences are invisible.
 */
export function mutateIcon(parent: Identicon, salt: string | number): Identicon {
  const key = `${parent.key}>${salt}`;
  const rng = mulberry32(fnv(key));
  return {
    grid: parent.grid.map((row) => row.slice()),
    hue: (parent.hue + 70 + Math.floor(rng() * 220)) % 360,
    key,
    error: false,
  };
}

/**
 * The same icon, marked as a failure. Rendered desaturated with a red ring.
 *
 * Idempotent, so marking an already-failed icon does not produce a second cache key
 * for a visually identical sprite.
 */
export function errIcon(icon: Identicon): Identicon {
  if (icon.error) return icon;
  return { grid: icon.grid, hue: icon.hue, key: `${icon.key}!`, error: true };
}

/**
 * Rasterise to a cached canvas.
 *
 * Cached by key and size because the packet layer draws hundreds of sprites per
 * frame and regenerating a 5x5 pattern each time would dominate the frame budget.
 * A canvas rather than the original's data URL: `drawImage` from a canvas needs no
 * decode step, where an `<img>` from a data URL does.
 */
const spriteCache = new Map<string, HTMLCanvasElement>();

export function iconSprite(icon: Identicon, px: number): HTMLCanvasElement {
  const key = `${icon.key}@${px}`;
  const hit = spriteCache.get(key);
  if (hit) return hit;

  const canvas = document.createElement("canvas");
  canvas.width = px;
  canvas.height = px;
  const ctx = canvas.getContext("2d")!;

  const inset = Math.round(px * 0.12);
  const area = px - inset * 2;
  const cell = area / GRID;

  ctx.fillStyle = icon.error ? `hsl(${icon.hue}, 18%, 45%)` : `hsl(${icon.hue}, 66%, 62%)`;
  for (let r = 0; r < GRID; r++) {
    for (let c = 0; c < COLS; c++) {
      if (!icon.grid[r]![c]) continue;
      fillCell(ctx, inset + c * cell, inset + r * cell, cell);
      // Mirror all but the centre column.
      if (c < COLS - 1) {
        fillCell(ctx, inset + (GRID - 1 - c) * cell, inset + r * cell, cell);
      }
    }
  }

  spriteCache.set(key, canvas);
  return canvas;
}

/** Overdraw by a fraction of a pixel so adjacent cells do not show seams. */
function fillCell(ctx: CanvasRenderingContext2D, x: number, y: number, size: number): void {
  ctx.fillRect(Math.round(x), Math.round(y), Math.ceil(size) + 0.6, Math.ceil(size) + 0.6);
}

/**
 * The icon for one traversal of one edge by one request.
 *
 * Derived rather than stored, so the trace stays small: a request's icon comes from
 * its id, and each edge it crosses recolours it. The response leg reuses the request
 * leg's icon, because it is the same call coming back rather than a new one.
 */
export function hopIcon(requestId: number, edgeId: string, failed: boolean): Identicon {
  // Namespaced, because node and edge ids are drawn from separate spaces and could
  // collide -- which would give a request the same icon on a pipe as at a station and
  // make a dock look like the sprite had not moved.
  const base = mutateIcon(rootIcon(requestId), `e:${edgeId}`);
  return failed ? errIcon(base) : base;
}

/** The icon shown in a station's occupancy row. */
export function visitIcon(requestId: number, nodeId: string, failed: boolean): Identicon {
  const base = mutateIcon(rootIcon(requestId), `n:${nodeId}`);
  return failed ? errIcon(base) : base;
}

/**
 * Data URL for DOM call sites -- the occupancy chips and the waterfall rows.
 *
 * Separately cached from the canvas because `toDataURL` re-encodes a PNG every call,
 * and these render inside React components that re-render on every playback publish.
 * Uncached this showed up as tens of encodes per second for icons that never change.
 */
const urlCache = new Map<string, string>();

export function iconDataUrl(icon: Identicon, px: number): string {
  const key = `${icon.key}@${px}`;
  const hit = urlCache.get(key);
  if (hit) return hit;
  const url = iconSprite(icon, px).toDataURL();
  urlCache.set(key, url);
  return url;
}

/** Clear the raster caches. Only needed when the device pixel ratio changes. */
export function clearIconCache(): void {
  spriteCache.clear();
  urlCache.clear();
}
