/**
 * Seeded pseudo-random number generation with independent streams.
 *
 * WHY THIS MATTERS MORE THAN IT LOOKS
 *
 * The legacy engine called the global `Math.random()` from a dozen places. Two
 * consequences, both fatal for an analysis tool:
 *
 *  1. Runs were not reproducible. A tool that gives a different answer each time
 *     cannot be used to compare two designs, which is the entire point.
 *
 *  2. Even with a seed, a SINGLE stream couples unrelated randomness. Change the
 *     server's replica count and the number of draws made for service times
 *     changes, which shifts every subsequent draw — including the arrival times.
 *     The two runs then differ in their workload as well as their configuration,
 *     so the difference in the result is not attributable to the change.
 *
 * Independent per-purpose streams give us "common random numbers": arrivals are
 * generated by their own stream, so changing capacity leaves the workload
 * bit-for-bit identical and an A/B diff is signal rather than noise. This is a
 * standard variance-reduction technique in discrete-event simulation, and it is
 * the difference between a comparison feature that works and one that lies.
 */

/** Named streams. Adding a purpose here must never perturb existing streams. */
export type StreamName =
  | "arrival"
  | "service"
  | "failure"
  | "network"
  | "routing"
  | "cache";

const STREAM_SALT: Record<StreamName, number> = {
  arrival: 0x9e3779b9,
  service: 0x85ebca6b,
  failure: 0xc2b2ae35,
  network: 0x27d4eb2f,
  routing: 0x165667b1,
  cache: 0xd3a2646c,
};

/**
 * mulberry32: a small, fast, well-distributed 32-bit generator.
 *
 * Chosen over `Math.random()` for reproducibility and over a cryptographic PRNG
 * for speed — a single run makes millions of draws and statistical quality at
 * this level is more than sufficient (it passes gjrand's basic suite).
 */
export class Rng {
  private state: number;

  constructor(seed: number) {
    // Avoid the degenerate all-zero state.
    this.state = (seed | 0) === 0 ? 0x6d2b79f5 : seed | 0;
  }

  /** Uniform in [0, 1). */
  next(): number {
    this.state = (this.state + 0x6d2b79f5) | 0;
    let t = this.state;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  }

  /**
   * Uniform in (0, 1] — excludes zero.
   *
   * Required wherever we take a logarithm (exponential and Pareto inversion).
   * `Math.log(0)` is -Infinity, which would produce an infinite service time and
   * silently wedge the simulation. One-in-four-billion bugs are the worst kind.
   */
  nextNonZero(): number {
    const u = this.next();
    return u === 0 ? Number.EPSILON : u;
  }

  /** Uniform integer in [0, n). */
  nextInt(n: number): number {
    return Math.floor(this.next() * n);
  }

  /** True with probability p. */
  chance(p: number): boolean {
    if (p <= 0) return false;
    if (p >= 1) return true;
    return this.next() < p;
  }

  /**
   * Standard normal via Box-Muller.
   *
   * The second variate is cached rather than discarded: throwing it away would
   * double the number of draws for lognormal service times, for nothing.
   */
  private spare: number | null = null;
  normal(): number {
    if (this.spare !== null) {
      const s = this.spare;
      this.spare = null;
      return s;
    }
    const u1 = this.nextNonZero();
    const u2 = this.next();
    const r = Math.sqrt(-2 * Math.log(u1));
    const theta = 2 * Math.PI * u2;
    this.spare = r * Math.sin(theta);
    return r * Math.cos(theta);
  }
}

/**
 * A bundle of independent streams derived from one run seed.
 *
 * Streams are derived by salting the seed per purpose, so two runs with the same
 * seed produce the same arrival sequence regardless of what else changed.
 */
export class RngBundle {
  private readonly streams = new Map<StreamName, Rng>();

  constructor(readonly seed: number) {}

  stream(name: StreamName): Rng {
    let rng = this.streams.get(name);
    if (!rng) {
      rng = new Rng((this.seed ^ STREAM_SALT[name]) | 0);
      this.streams.set(name, rng);
    }
    return rng;
  }
}
